source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

target 'SimpleExample' do
    
    pod 'YYText'
    
    pod 'RxSwift'
    pod 'RxCocoa'
#    pod 'RxGesture'
    pod 'SnapKit'
    pod 'Then'

end
